[build]
  base = "Frontend"
  command = "npm install && npm run build"
  publish = "Frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200