services:
  - type: web
    name: qhse-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qhse-db
          property: connectionString

databases:
  - name: qhse-db
    databaseName: qhse
    plan: free