services:
  - type: web
    name: qhse-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    python:
      version: "3.12.4"   # ‚Üê AJOUTEZ CETTE LIGNE
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qhse-database
          property: connectionString